#!/bin/bash
# A12 -- full 977-event confirmation. Same runner, the 977 ntuple and the 977 LST reference
# regenerated by the Baseline agent this round.
S=/mnt/data1/gsn27/here/CMSSW_17_0_0_pre2/src/RecoTracker/LSTCore/standalone
export LSTN="$S/rebase_ref/LSTNtuple_instr_977evt.root"
export BASEHISTS="$S/fin_ref/fin_base977_hists.root"
TAG="$1"; shift
bash $S/a12_ref/a12_run.sh "$TAG" "$@"
