#ifndef RecoTracker_MkFitAlpaka_interface_matriplex_MatriplexOps_h
#define RecoTracker_MkFitAlpaka_interface_matriplex_MatriplexOps_h

// Generic dense similarity out = A * B * A^T (A: 6x6, B and out: symmetric 6x6), generated by the stock GenMul.pm
// (gen/gen_similarity.pl) the same way stock GenMPlexOps.pl generates MultHelixProp/MultHelixPropTransp, without a
// sparsity pattern. Stock mkFit has no generic similarity: propagation/Kalman use pattern-specialized .ah products
// (owned by the prop lane; regenerate them with gen/GenMul.pm, method dump_multiply_portable).

#include "RecoTracker/MkFitAlpaka/interface/matriplex/Matrix.h"

namespace mkfitdev {

  // Serial backend, benchmark kernel of test_mplex.dev.cc: forcing the two products inline (but not similarityLL
  // itself) gave 9.2 ns per chained similarity vs 15.1 ns (nothing forced) and 12.7 ns (everything forced).

  // temp = A * B
  template <Matriplex::idx_t N>
  ALPAKA_FN_HOST_ACC ALPAKA_FN_INLINE void multSimilarityLL(const MPlexLL<N>& A, const MPlexLS<N>& B, MPlexLL<N>& C) {
    const float* a = A.fArray;
    const float* b = B.fArray;
    float* c = C.fArray;
#include "RecoTracker/MkFitAlpaka/interface/matriplex/SimilarityLL.ah"
  }

  // out = temp * A^T (symmetric result, lower triangle computed)
  template <Matriplex::idx_t N>
  ALPAKA_FN_HOST_ACC ALPAKA_FN_INLINE void multSimilarityLLTransp(const MPlexLL<N>& A,
                                                                  const MPlexLL<N>& B,
                                                                  MPlexLS<N>& C) {
    const float* a = A.fArray;
    const float* b = B.fArray;
    float* c = C.fArray;
#include "RecoTracker/MkFitAlpaka/interface/matriplex/SimilarityLLTransp.ah"
  }

  template <Matriplex::idx_t N>
  ALPAKA_FN_HOST_ACC void similarityLL(const MPlexLL<N>& A, const MPlexLS<N>& B, MPlexLS<N>& out) {
    MPlexLL<N> temp;
    multSimilarityLL(A, B, temp);
    multSimilarityLLTransp(A, temp, out);
  }

}  // namespace mkfitdev

#endif
