#!/usr/bin/env python3
"""ANGLE 7 exporter: emits edge_mlp_weights.h for EITHER

  --variant wide    40 -> H -> H -> 1                  (plain nn.Sequential)
  --variant e2head  trunk 40 -> H (ReLU) + TWO heads H -> H -> 1 keyed by ef_etype

Same conventions as export_weights.py (transposed wgt[in][out], conditioning baked
into kClipLo/kClipHi/kLog10p1). The generated header ALWAYS carries two head weight
sets; for --variant wide head B is a byte copy of head A and kSplitHeads is false, so
the C++ code path is identical and single-head models stay bit-identical.
"""
import argparse
import json
import os
import sys

D = os.path.dirname(os.path.abspath(__file__))
N_NODE_FEAT = 13
N_EDGE_FEAT = 14
UNCLIPPED = 1e30


def f32(v):
    import numpy as np
    s = f"{float(np.float32(v)):.9g}"
    if "." not in s and "e" not in s and "n" not in s and "i" not in s:
        s += ".0"
    return s + "f"


def a1(vals, per_line=6, indent="    "):
    lines = [indent + ", ".join(f32(v) for v in vals[i:i + per_line]) + ","
             for i in range(0, len(vals), per_line)]
    return "{\n" + "\n".join(lines)[:-1] + "\n}"


def a2(mat, indent="    "):
    return "{\n" + ",\n".join(indent + a1(r, 6, indent + "    ") for r in mat) + "\n}"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--variant", choices=["wide", "e2head"], required=True)
    p.add_argument("--model", required=True)
    p.add_argument("--norm", required=True)
    p.add_argument("--out", default=os.path.join(D, "edge_mlp_weights.h"))
    args = p.parse_args()
    import torch

    blob = torch.load(args.model, map_location="cpu", weights_only=False)
    sd = blob["state_dict"]
    norm = json.load(open(args.norm))
    names, mean, std = norm["feature_names"], norm["mean"], norm["std"]
    n_in = len(names)
    assert n_in == 2 * N_NODE_FEAT + N_EDGE_FEAT
    for j, nm in enumerate(names):
        pre = "ni_" if j < N_NODE_FEAT else ("no_" if j < 2 * N_NODE_FEAT else "ef_")
        assert nm.startswith(pre), f"slot {j}: {nm} not {pre}*"
    assert names[2 * N_NODE_FEAT] == "ef_etype", "ef_etype must be edge-feature slot 0"

    clip_lo = [-UNCLIPPED] * n_in
    clip_hi = [UNCLIPPED] * n_in
    log10p1 = [False] * n_in
    for c in norm.get("conditioning") or []:
        j = names.index(c["feature"])
        if c["op"] == "clip":
            clip_lo[j], clip_hi[j] = c["lo"], c["hi"]
        elif c["op"] == "log10_1p":
            log10p1[j] = True
        else:
            raise ValueError(c["op"])

    def t(k):
        return sd[k].to(torch.float32).tolist()

    if args.variant == "wide":
        w1, b1 = t("0.weight"), t("0.bias")
        heads = [(t("2.weight"), t("2.bias"), t("4.weight")[0], t("4.bias")[0])] * 2
        split = "false"
    else:
        w1, b1 = t("trunk.0.weight"), t("trunk.0.bias")
        heads = [(t(f"head{h}.0.weight"), t(f"head{h}.0.bias"),
                  t(f"head{h}.2.weight")[0], t(f"head{h}.2.bias")[0]) for h in (1, 2)]
        split = "true"
    n_hid = len(b1)
    assert len(w1) == n_hid and len(w1[0]) == n_in

    w1_t = [[w1[o][i] for o in range(n_hid)] for i in range(n_in)]
    blocks = []
    for tag, (w2, b2, wo, bo) in zip(("", "b"), heads):
        w2_t = [[w2[o][i] for o in range(n_hid)] for i in range(n_hid)]
        blocks.append(f"""constexpr float wgt_l2{tag}[kHidden][kHidden] = {a2(w2_t)};

constexpr float bias_l2{tag}[kHidden] = {a1(b2)};

constexpr float wgt_out{tag}[kHidden] = {a1(wo)};

constexpr float bias_out{tag} = {f32(bo)};
""")

    feat_comment = "\n".join(f"//  [{j:2d}] {nm}" for j, nm in enumerate(names))
    hdr = f"""// GENERATED by export_weights_a7.py -- DO NOT EDIT BY HAND.
// variant: {args.variant}
// model: {args.model}
// norm:  {args.norm}
// Model meta: best_epoch={blob.get('best_epoch')} best_val_auc={blob.get('best_val_auc')}
//
// Convention (mirrors src/alpaka/NeuralNetwork.h): weights are stored TRANSPOSED,
// wgt[in][out], so the inner loop is output[o] += input[i] * wgt[i][o].
// Per-input preprocessing order: log10(1+x) if kLog10p1 -> clip -> (x-mean)/std.
//
// TWO HEADS: layer 1 (wgt_l1/bias_l1) is the shared trunk; the second linear +
// output layers exist twice. kSplitHeads==false -> the "b" set is a copy of the "a"
// set and the model is a plain 3-layer MLP. kSplitHeads==true -> rows with
// ef_etype >= 1.5 (E2, shared-LS edges) use the "b" set.
//
// Input feature order (ni_00..ni_12, no_00..no_12, ef_00..ef_13):
{feat_comment}
#ifndef PROTOTYPE_EDGE_MLP_WEIGHTS_H
#define PROTOTYPE_EDGE_MLP_WEIGHTS_H

namespace edgemlp {{

constexpr int kInput = {n_in};
constexpr int kHidden = {n_hid};
constexpr bool kSplitHeads = {split};

constexpr float kFeatMean[kInput] = {a1(mean)};

constexpr float kFeatStd[kInput] = {a1(std)};

constexpr float kClipLo[kInput] = {a1(clip_lo)};

constexpr float kClipHi[kInput] = {a1(clip_hi)};

constexpr bool kLog10p1[kInput] = {{{", ".join("true" if v else "false" for v in log10p1)}}};

constexpr float wgt_l1[kInput][kHidden] = {a2(w1_t)};

constexpr float bias_l1[kHidden] = {a1(b1)};

{blocks[0]}
{blocks[1]}
}}  // namespace edgemlp

#endif
"""
    open(args.out, "w").write(hdr)
    print(f"wrote {args.out}: variant={args.variant} kInput={n_in} kHidden={n_hid} "
          f"kSplitHeads={split}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
