#!/bin/bash
# A06 FINAL -- full 977-event confirmation of the recommendation and of the -L variant.
# LST reference = fin_ref/fin_base977_hists.root (generated by the Baseline agent).
S=/mnt/data1/gsn27/here/CMSSW_17_0_0_pre2/src/RecoTracker/LSTCore/standalone
P="$S/a06_ref"
launch() { tag="$1"; shift; LSTN="$S/rebase_ref/LSTNtuple_instr_977evt.root" \
  BASEHISTS="$S/fin_ref/fin_base977_hists.root" \
  setsid nohup bash "$S/a06_ref/a06_run.sh" "$tag" "$@" > "$P/nh_${tag}.out" 2>&1 < /dev/null & }
launch W_EW50  -EXW 0.50 -EXR 4.0
launch W_L5    -EXW 0.50 -EXR 4.0 -L 5.0
launch W_R4    -EXR 4.0
sleep 5
echo "[a06] 977 BATCH LAUNCHED"
