#!/usr/bin/env python3
"""A5: export the two-pass (K4-lite context) edge head to a constexpr C++ header.

Same convention as export_weights.py (production NeuralNetwork.h style): weights
TRANSPOSED wgt[in][out], preprocessing baked in, generated file never hand-edited.

Input layout of the head (frozen by a5_twopass.py's VARIANT_COLS):
  [0:40]  the 40 raw edge/node features, v3-CONDITIONED (log10_1p/clip from
          edge_norm_v3.json) but standardized with the HEAD's own mean/std
  [40]    (variant B only) the pass-1 v3 logit
  [last4] ctxOutMean, ctxOutMax, ctxInMean, ctxInMax  (leave-one-out junction
          context over pass-1 logits, SENTINEL when the competitor set is empty,
          clipped to +-20 BEFORE standardization)
"""

import argparse
import json
import os

MINE = os.path.dirname(os.path.abspath(__file__))
PROTO = "/mnt/data1/gsn27/here/CMSSW_17_0_0_pre2/src/RecoTracker/LSTCore/standalone/prototype"
UNCLIPPED = 1e30


def f32(v):
    import numpy as np
    s = f"{float(np.float32(v)):.9g}"
    if "." not in s and "e" not in s and "n" not in s and "i" not in s:
        s += ".0"
    return s + "f"


def arr1(vals, per_line=6, indent="    "):
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append(indent + ", ".join(f32(v) for v in vals[i:i + per_line]) + ",")
    return "{\n" + "\n".join(lines)[:-1] + "\n}"


def arr2(mat, indent="    "):
    rows = [indent + arr1(r, 6, indent + "    ") for r in mat]
    return "{\n" + ",\n".join(rows) + "\n}"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--head", default=f"{MINE}/a5_head_B.pt")
    p.add_argument("--norm", default=f"{PROTO}/edge_norm_v3.json")
    p.add_argument("--out", default=f"{MINE}/a5_head_weights.h")
    args = p.parse_args()
    import numpy as np
    import torch

    blob = torch.load(args.head, map_location="cpu", weights_only=False)
    sd = blob["state_dict"]
    n_in, n_hid, _ = blob["arch"]
    cols = blob["cols"]
    mean = blob["mean"]
    std = blob["std"]
    sent = blob["sentinel"]
    use_pass1 = 40 in cols
    assert cols[:40] == list(range(40)), "first 40 columns must be the raw features"
    assert cols[-4:] == [41, 42, 43, 44], "last 4 columns must be the context block"
    assert n_in == len(cols) == len(mean) == len(std)

    norm = json.load(open(args.norm))
    names = norm["feature_names"]
    log10p1 = [0] * 40
    clip_lo = [-UNCLIPPED] * 40
    clip_hi = [UNCLIPPED] * 40
    for c in norm["conditioning"]:
        j = names.index(c["feature"])
        if c["op"] == "clip":
            clip_lo[j], clip_hi[j] = c["lo"], c["hi"]
        elif c["op"] == "log10_1p":
            log10p1[j] = 1
        else:
            raise ValueError(c["op"])

    # this torch build has no numpy interop (.numpy() raises) -> go via tolist()
    w1 = sd["0.weight"].tolist()             # [hid][in]
    b1 = sd["0.bias"].tolist()
    wo = sd["2.weight"].tolist()[0]          # [1][hid] -> [hid]
    bo = float(sd["2.bias"].tolist()[0])
    w1t = [[w1[o][i] for o in range(len(w1))] for i in range(len(w1[0]))]  # -> [in][hid]

    lines = []
    lines.append("// GENERATED by export_a5_head.py -- DO NOT EDIT BY HAND.")
    lines.append(f"//   head: {os.path.basename(args.head)}  (arch {blob['arch']}, "
                 f"best_val_auc={blob['best_val_auc']:.5f} @ epoch {blob['best_epoch']})")
    lines.append(f"//   raw-feature conditioning from {os.path.basename(args.norm)} (v3, unchanged)")
    lines.append("//")
    lines.append("// Input assembly (A5 two-pass edge scoring):")
    lines.append("//   [0..39]  raw features, conditioning -> standardize with kMean/kStd")
    lines.append(f"//   [40]     pass-1 v3 logit           {'INCLUDED' if use_pass1 else 'NOT included'}")
    lines.append("//   [last 4] ctxOutMean, ctxOutMax, ctxInMean, ctxInMax (clip +-20 -> standardize)")
    lines.append("")
    lines.append("#ifndef PROTOTYPE_A5_HEAD_WEIGHTS_H")
    lines.append("#define PROTOTYPE_A5_HEAD_WEIGHTS_H")
    lines.append("")
    lines.append("namespace a5head {")
    lines.append(f"constexpr int kInput = {n_in};")
    lines.append(f"constexpr int kHidden = {n_hid};")
    lines.append(f"constexpr bool kUsePass1 = {'true' if use_pass1 else 'false'};")
    lines.append(f"constexpr float kSentinel = {f32(sent)};")
    lines.append("constexpr float kCtxClip = 20.0f;")
    lines.append(f"constexpr int kRawLog10p1[40] = {{{', '.join(str(v) for v in log10p1)}}};")
    lines.append(f"constexpr float kRawClipLo[40] = {arr1(clip_lo)};")
    lines.append(f"constexpr float kRawClipHi[40] = {arr1(clip_hi)};")
    lines.append(f"constexpr float kMean[kInput] = {arr1(mean)};")
    lines.append(f"constexpr float kStd[kInput] = {arr1(std)};")
    lines.append(f"constexpr float wgt_l1[kInput][kHidden] = {arr2(w1t)};")
    lines.append(f"constexpr float bias_l1[kHidden] = {arr1(b1)};")
    lines.append(f"constexpr float wgt_out[kHidden] = {arr1(wo)};")
    lines.append(f"constexpr float bias_out = {f32(bo)};")
    lines.append("}  // namespace a5head")
    lines.append("")
    lines.append("#endif")
    with open(args.out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {args.out} (kInput={n_in}, kHidden={n_hid}, usePass1={use_pass1})")


if __name__ == "__main__":
    main()
