#!/usr/bin/env python3
"""Export the ANGLE-B3 3-CLASS edge head to a constexpr C++ header (namespace edge3mlp).

Identical convention to export_weights.py (transposed wgt[in][out], conditioning baked
into kClipLo/kClipHi/kLog10p1, then standardize) except the output layer has THREE units:
  wgt_out[kHidden][kOutput], bias_out[kOutput], kOutput = 3
  class 0 = fake, 1 = prompt-true (simVxy < 1 cm), 2 = displaced-true.

A SENTINEL header (all-zero output layer) is emitted by --sentinel so the tree compiles
before the model exists; EdgeInference::edgeHead3Available() detects it.

Usage:
  python3 export_edge3_weights.py --model edge3_mlp_v1.pt --norm edge3_norm_v1.json
"""

import argparse
import json
import os
import sys

PROTO_DIR = os.path.dirname(os.path.abspath(__file__))
EXPECTED_ARCH = [40, 32, 32, 3]
N_NODE_FEAT = 13
N_EDGE_FEAT = 14
UNCLIPPED = 1e30


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--model", default=os.path.join(PROTO_DIR, "edge3_mlp_v1.pt"))
    p.add_argument("--norm", default=os.path.join(PROTO_DIR, "edge3_norm_v1.json"))
    p.add_argument("--out", default=os.path.join(PROTO_DIR, "edge3_mlp_weights.h"))
    p.add_argument("--sentinel", action="store_true",
                   help="emit an all-zero placeholder header (no model needed)")
    return p.parse_args()


def f32(v):
    import numpy as np
    s = f"{float(np.float32(v)):.9g}"
    if "." not in s and "e" not in s and "n" not in s and "i" not in s:
        s += ".0"
    return s + "f"


def fmt1(vals, per_line=6, indent="    "):
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append(indent + ", ".join(f32(v) for v in vals[i:i + per_line]) + ",")
    return "{\n" + "\n".join(lines)[:-1] + "\n}"


def fmt2(mat, indent="    "):
    rows = [indent + fmt1(row, per_line=6, indent=indent + "    ") for row in mat]
    return "{\n" + ",\n".join(rows) + "\n}"


def main():
    args = parse_args()

    n_in, n_hid, n_out = 40, 32, 3
    if args.sentinel:
        names = ([f"ni_{i:02d}" for i in range(N_NODE_FEAT)]
                 + [f"no_{i:02d}" for i in range(N_NODE_FEAT)]
                 + [f"ef_{i:02d}" for i in range(N_EDGE_FEAT)])
        mean = [0.0] * n_in
        std = [1.0] * n_in
        clip_lo = [-UNCLIPPED] * n_in
        clip_hi = [UNCLIPPED] * n_in
        log10p1 = [False] * n_in
        w1_t = [[0.0] * n_hid for _ in range(n_in)]
        b1 = [0.0] * n_hid
        w2_t = [[0.0] * n_hid for _ in range(n_hid)]
        b2 = [0.0] * n_hid
        wo_t = [[0.0] * n_out for _ in range(n_hid)]
        bo = [0.0] * n_out
        meta = "SENTINEL (untrained placeholder)"
    else:
        import torch
        blob = torch.load(args.model, map_location="cpu", weights_only=False)
        sd = blob["state_dict"]
        arch = blob.get("arch")
        assert arch == EXPECTED_ARCH, f"unexpected arch {arch}"
        n_in, n_hid, n_out = arch[0], arch[1], arch[3]
        with open(args.norm) as fh:
            norm = json.load(fh)
        names, mean, std = norm["feature_names"], norm["mean"], norm["std"]
        assert len(names) == n_in == len(mean) == len(std)
        assert n_in == 2 * N_NODE_FEAT + N_EDGE_FEAT
        for j, nm in enumerate(names):
            pre = "ni_" if j < N_NODE_FEAT else ("no_" if j < 2 * N_NODE_FEAT else "ef_")
            assert nm.startswith(pre), f"slot {j}: {nm} not {pre}*"
        clip_lo = [-UNCLIPPED] * n_in
        clip_hi = [UNCLIPPED] * n_in
        log10p1 = [False] * n_in
        for c in (norm.get("conditioning") or []):
            j = names.index(c["feature"])
            if c["op"] == "clip":
                clip_lo[j], clip_hi[j] = c["lo"], c["hi"]
            elif c["op"] == "log10_1p":
                log10p1[j] = True
            else:
                raise ValueError(c["op"])

        def t2l(k):
            return sd[k].to(torch.float32).tolist()

        w1, b1 = t2l("0.weight"), t2l("0.bias")
        w2, b2 = t2l("2.weight"), t2l("2.bias")
        wo, bo = t2l("4.weight"), t2l("4.bias")
        assert len(wo) == n_out and len(wo[0]) == n_hid and len(bo) == n_out
        w1_t = [[w1[o][i] for o in range(n_hid)] for i in range(n_in)]
        w2_t = [[w2[o][i] for o in range(n_hid)] for i in range(n_hid)]
        wo_t = [[wo[o][j] for o in range(n_out)] for j in range(n_hid)]
        meta = (f"best_epoch={blob.get('best_epoch')} best_val_sel={blob.get('best_val_sel')} "
                f"warm_start={blob.get('warm_start')} seed={blob.get('seed')} arch={arch}")

    feat_comment = "\n".join(f"//  [{j:2d}] {nm}" for j, nm in enumerate(names))
    hdr = f"""// GENERATED by export_edge3_weights.py -- DO NOT EDIT BY HAND.
// Sources: model {args.model} / norm {args.norm}
// Model meta: {meta}
//
// ANGLE-B3 3-CLASS EDGE HEAD. Same convention as edge_mlp_weights.h (transposed
// wgt[in][out]; per-input log10_1p -> clip -> standardize) with a 3-unit output:
//   out[0] fake, out[1] prompt-true (simVxy < 1 cm), out[2] displaced-true.
// Decision margins: mP = out1-out0, mD = out2-out0, mX = max(out1,out2)-out0,
// mS = logsumexp(out1,out2)-out0 (the exact 2-class-equivalent log-odds).
//
// Input feature order (ni_00..ni_12, no_00..no_12, ef_00..ef_13):
{feat_comment}
#ifndef PROTOTYPE_EDGE3_MLP_WEIGHTS_H
#define PROTOTYPE_EDGE3_MLP_WEIGHTS_H

namespace edge3mlp {{

constexpr int kInput = {n_in};
constexpr int kHidden = {n_hid};
constexpr int kOutput = {n_out};

constexpr float kFeatMean[kInput] = {fmt1(mean)};

constexpr float kFeatStd[kInput] = {fmt1(std)};

constexpr float kClipLo[kInput] = {fmt1(clip_lo)};

constexpr float kClipHi[kInput] = {fmt1(clip_hi)};

constexpr bool kLog10p1[kInput] = {{{", ".join("true" if v else "false" for v in log10p1)}}};

constexpr float wgt_l1[kInput][kHidden] = {fmt2(w1_t)};

constexpr float bias_l1[kHidden] = {fmt1(b1)};

constexpr float wgt_l2[kHidden][kHidden] = {fmt2(w2_t)};

constexpr float bias_l2[kHidden] = {fmt1(b2)};

constexpr float wgt_out[kHidden][kOutput] = {fmt2(wo_t)};

constexpr float bias_out[kOutput] = {fmt1(bo)};

}}  // namespace edge3mlp

#endif
"""
    with open(args.out, "w") as fh:
        fh.write(hdr)
    print(f"wrote {args.out}: kInput={n_in} kHidden={n_hid} kOutput={n_out}"
          + (" [SENTINEL]" if args.sentinel else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
