#include "AttachInference.h"

#include "PixelAttach.h"  // kAttachFeat

// Weights header presence switches between the real MLP and the -1 sentinel path
// (AttachInference.h). attach_mlp_weights.h is generated by the future export script
// (mirroring export_chain_weights.py); until it exists this TU compiles the sentinel.
#if __has_include("attach_mlp_weights.h")
#define HAVE_ATTACH_WEIGHTS 1
#include "attach_mlp_weights.h"
#else
#define HAVE_ATTACH_WEIGHTS 0
#endif

#if HAVE_ATTACH_WEIGHTS

#include <algorithm>
#include <cmath>

// Same implementation pattern as ChainInference.cc / production NeuralNetwork.h.
#if defined(__GNUC__) && !defined(__clang__)
#define ATTACHMLP_UNROLL_LOOP _Pragma("GCC ivdep")
#else
#define ATTACHMLP_UNROLL_LOOP
#endif

namespace {

  template <int IN_FEATURES, int OUT_FEATURES>
  inline void linear_layer(const float (&input)[IN_FEATURES],
                           float (&output)[OUT_FEATURES],
                           const float (&weights)[IN_FEATURES][OUT_FEATURES],
                           const float (&biases)[OUT_FEATURES]) {
    ATTACHMLP_UNROLL_LOOP
    for (int i = 0; i < OUT_FEATURES; ++i) {
      output[i] = biases[i];
      ATTACHMLP_UNROLL_LOOP
      for (int j = 0; j < IN_FEATURES; ++j) {
        output[i] += input[j] * weights[j][i];
      }
    }
  }

  template <int FEATURES>
  inline void relu_activation(float (&input)[FEATURES]) {
    ATTACHMLP_UNROLL_LOOP
    for (int col = 0; col < FEATURES; ++col) {
      input[col] = (input[col] > 0.f) ? input[col] : 0.f;
    }
  }

  // Per-input preprocessing baked into the generated header: optional log10(1+x) ->
  // clip -> standardize (same contract as chainmlp).
  inline float preprocess(float x, int i) {
    if (attachmlp::kLog10p1[i])
      x = std::log10(1.f + x);
    x = std::min(std::max(x, attachmlp::kClipLo[i]), attachmlp::kClipHi[i]);
    return (x - attachmlp::kFeatMean[i]) / attachmlp::kFeatStd[i];
  }

}  // namespace

bool attachHeadAvailable() { return true; }

float attachLogit(const float* f) {
  // M16: the layout grew from 18 to 19 (feature 18 = targetType) while slots 0..17 kept
  // their definitions and order EXACTLY. A head trained on the old 18-slot layout (the
  // M7 attach_mlp_weights.h) therefore stays valid for CHAIN targets and is fed the
  // leading kInput features verbatim -- bit-identical to pre-M16 scoring. A head trained
  // on the general layout has kInput == kAttachFeat and consumes targetType too. Only an
  // OVER-long head (kInput > kAttachFeat) is a real contract violation.
  static_assert(attachmlp::kInput <= kAttachFeat, "attach_mlp_weights.h input size exceeds the PixelAttach.h layout");

  float x[attachmlp::kInput];
  ATTACHMLP_UNROLL_LOOP
  for (int i = 0; i < attachmlp::kInput; ++i)
    x[i] = preprocess(f[i], i);

  float x1[attachmlp::kHidden];
  float x2[attachmlp::kHidden];

  linear_layer<attachmlp::kInput, attachmlp::kHidden>(x, x1, attachmlp::wgt_l1, attachmlp::bias_l1);
  relu_activation<attachmlp::kHidden>(x1);

  linear_layer<attachmlp::kHidden, attachmlp::kHidden>(x1, x2, attachmlp::wgt_l2, attachmlp::bias_l2);
  relu_activation<attachmlp::kHidden>(x2);

  float logit = attachmlp::bias_out;
  ATTACHMLP_UNROLL_LOOP
  for (int j = 0; j < attachmlp::kHidden; ++j)
    logit += x2[j] * attachmlp::wgt_out[j];

  return logit;
}

#else  // sentinel mode: no trained head yet (PixelAttach.h contract)

bool attachHeadAvailable() { return false; }

float attachLogit(const float*) { return 0.f; }

#endif
