#!/usr/bin/env python3
"""Export the A02 dedup head (torch state_dict + norm json) to a constexpr C++ header,
following export_attach_weights.py / the production NeuralNetwork.h convention: weights
are emitted TRANSPOSED (torch Linear stores [out,in]; the header stores wgt[in][out]) so
the C++ inner loop is output[o] += input[i] * wgt[i][o].

Preprocessing baked in: clip to the training percentiles, then standardize. There is no
log10_1p stage -- every nonlinear conditioning the dedup features need is already applied
in the C++ feature builder, so the dump and the inference input are the same numbers.

The output header's existence FLIPS DedupInference.cc from the sentinel path to the real
MLP (__has_include switch) -- rebuild after export.
"""

import argparse
import json
import os
import sys

PROTO_DIR = os.path.dirname(os.path.abspath(__file__))


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--model", required=True)
    p.add_argument("--norm", required=True)
    p.add_argument("--out", default=os.path.join(PROTO_DIR, "dedup_mlp_weights.h"))
    return p.parse_args()


def f32(v):
    import numpy as np
    s = f"{float(np.float32(v)):.9g}"
    if "." not in s and "e" not in s and "n" not in s and "i" not in s:
        s += ".0"
    return s + "f"


def fmt_array_1d(vals, per_line=6, indent="    "):
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append(indent + ", ".join(f32(v) for v in vals[i:i + per_line]) + ",")
    body = "\n".join(lines)[:-1]
    return "{\n" + body + "\n}"


def fmt_array_2d(mat, indent="    "):
    rows = [indent + fmt_array_1d(row, per_line=6, indent=indent + "    ") for row in mat]
    return "{\n" + ",\n".join(rows) + "\n}"


def main():
    args = parse_args()
    import torch

    try:
        blob = torch.load(args.model, map_location="cpu")
    except Exception:
        blob = torch.load(args.model, map_location="cpu", weights_only=False)
    sd = blob["state_dict"]
    arch = blob["arch"]
    n_in, n_hid = arch[0], arch[1]
    assert arch[2] == n_hid and arch[3] == 1, f"unexpected arch {arch}"

    with open(args.norm) as fh:
        norm = json.load(fh)
    names = norm["feature_names"]
    mean, std = norm["mean"], norm["std"]
    clip_lo, clip_hi = norm["clip_lo"], norm["clip_hi"]
    assert len(names) == n_in == len(mean) == len(std) == len(clip_lo) == len(clip_hi)
    if blob.get("feature_names") is not None:
        assert blob["feature_names"] == names, "model/norm feature_names disagree"

    def t2l(key):
        return sd[key].to(torch.float32).tolist()

    w1, b1 = t2l("0.weight"), t2l("0.bias")
    w2, b2 = t2l("2.weight"), t2l("2.bias")
    wo, bo = t2l("4.weight"), t2l("4.bias")
    assert len(w1) == n_hid and len(w1[0]) == n_in
    assert len(w2) == n_hid and len(w2[0]) == n_hid
    assert len(wo) == 1 and len(wo[0]) == n_hid and len(bo) == 1

    w1_t = [[w1[o][i] for o in range(n_hid)] for i in range(n_in)]
    w2_t = [[w2[o][i] for o in range(n_hid)] for i in range(n_hid)]
    wo_t = wo[0]

    feat_comment = "\n".join(f"//  [{j:2d}] {nm}" for j, nm in enumerate(names))
    cmd = "python3 export_dedup_weights.py " + " ".join(
        f"--{k} {getattr(args, k)}" for k in ("model", "norm", "out"))

    hdr = f"""// GENERATED by export_dedup_weights.py -- DO NOT EDIT BY HAND.
// Sources:
//   model: {args.model}
//   norm:  {args.norm}
// Command:
//   {cmd}
// Model meta: best_epoch={blob.get('best_epoch')} best_val_score={blob.get('best_val_score')}
//             seed={blob.get('seed')} arch={arch}
//
// Convention (mirrors src/alpaka/NeuralNetwork.h): weights are stored TRANSPOSED,
// wgt[in][out], so the inference inner loop is output[o] += input[i] * wgt[i][o].
//
// Per-input preprocessing, applied in this order:
//   1. x = min(max(x, kClipLo[i]), kClipHi[i])
//   2. x = (x - kFeatMean[i]) / kFeatStd[i]
//
// Input feature order (the kDedupFeat contract, DedupInference.h):
{feat_comment}
#ifndef PROTOTYPE_DEDUP_MLP_WEIGHTS_H
#define PROTOTYPE_DEDUP_MLP_WEIGHTS_H

namespace dedupmlp {{

constexpr int kInput = {n_in};
constexpr int kHidden = {n_hid};

constexpr float kFeatMean[kInput] = {fmt_array_1d(mean)};

constexpr float kFeatStd[kInput] = {fmt_array_1d(std)};

constexpr float kClipLo[kInput] = {fmt_array_1d(clip_lo)};

constexpr float kClipHi[kInput] = {fmt_array_1d(clip_hi)};

constexpr float wgt_l1[kInput][kHidden] = {fmt_array_2d(w1_t)};

constexpr float bias_l1[kHidden] = {fmt_array_1d(b1)};

constexpr float wgt_l2[kHidden][kHidden] = {fmt_array_2d(w2_t)};

constexpr float bias_l2[kHidden] = {fmt_array_1d(b2)};

constexpr float wgt_out[kHidden] = {fmt_array_1d(wo_t)};

constexpr float bias_out = {f32(bo[0])};

}}  // namespace dedupmlp

#endif
"""
    with open(args.out, "w") as fh:
        fh.write(hdr)
    n_par = n_in * n_hid + n_hid + n_hid * n_hid + n_hid + n_hid + 1
    print(f"wrote {args.out}: kInput={n_in} kHidden={n_hid} ({n_par} parameters)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
