#!/usr/bin/env python3

# WROTE THE SHIPPED src/alpaka/AttachNetworkWeights.h from the trained model (jet round 3, ATJ25R).
# Byte-verified against the shipped header. Emits the prototype namespace form; the in-tree header
# is the same payload rewrapped in ALPAKA_ACCELERATOR_NAMESPACE::lst::dnn::attachmlp.

"""AT: regenerate src/alpaka/AttachNetworkWeights.h from a train_s3.py checkpoint + its norm json.

`b1_ref/port_hdr.py` (the tool deploy_s3.sh used) was purged in the 2026-08-11 disk cleanup, so
this is its replacement.  It is VERIFIED rather than trusted: run with --verify <shipped header>
and it regenerates the SHIPPED header from models/A2_cos3e3.pt and asserts byte identity, which is
a stronger check than port_hdr.py's "PORT VERIFIED" line.

usage: export_hdr.py --model X.pt --norm X_norm.json --out hdr.h [--verify <existing header>]
                     [--cmd "<the invocation to record in the banner>"]
"""
import argparse
import json
import os

import numpy as np

UNCLIPPED = 1e30


def f32(v):
    s = "%.9g" % float(np.float32(v))
    if "." not in s and "e" not in s and "n" not in s and "i" not in s:
        s += ".0"
    return s + "f"


def arr1(vals, per_line=6, indent="      "):
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append(indent + ", ".join(f32(v) for v in vals[i:i + per_line]) + ",")
    body = "\n".join(lines)[:-1]
    return "{\n" + body + "\n  }"


def arr2(rows, per_line=6):
    out = []
    for r in rows:
        out.append("      " + arr1(r, per_line, "          "))
    return "{\n" + ",\n".join(out) + "\n  }"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True)
    ap.add_argument("--norm", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--verify")
    ap.add_argument("--cmd", default="")
    a = ap.parse_args()

    import torch
    blob = torch.load(a.model, map_location="cpu", weights_only=False)
    sd = blob["state_dict"]
    tonp = lambda t: np.array(t.detach().cpu().tolist(), dtype=np.float64)
    w1 = tonp(sd["0.weight"]); b1 = tonp(sd["0.bias"])
    w2 = tonp(sd["2.weight"]); b2 = tonp(sd["2.bias"])
    wo = tonp(sd["4.weight"]); bo = tonp(sd["4.bias"])
    assert wo.shape[0] == 1, "only the scalar-output head is expressible in AttachInference.cc"
    n_in, n_hid = w1.shape[1], w1.shape[0]

    nm = json.load(open(a.norm))
    names = nm["feature_names"]
    assert len(names) == n_in
    mean = nm["mean"]; std = nm["std"]
    clip_lo = [-UNCLIPPED] * n_in
    clip_hi = [UNCLIPPED] * n_in
    log10p1 = [False] * n_in
    for c in nm["conditioning"]:
        i = names.index(c["feature"])
        if c["op"] == "log10_1p":
            log10p1[i] = True
        elif c["op"] == "clip":
            clip_lo[i] = c["lo"]; clip_hi[i] = c["hi"]
        else:
            raise SystemExit("unknown conditioning op %s" % c["op"])

    meta = "best_epoch=%s best_val_auc=%s" % (blob.get("best_epoch"), blob.get("best_val_auc"))
    seed = blob.get("seed")
    banner = []
    banner.append("// GENERATED by export_attach_weights.py -- DO NOT EDIT BY HAND.")
    banner.append("// Sources:")
    banner.append("//   model: %s" % os.path.abspath(a.model))
    banner.append("//   norm:  %s" % os.path.abspath(a.norm))
    banner.append("// Command:")
    banner.append("//   %s" % (a.cmd or "python3 export_attach_weights.py --model %s --norm %s --out %s"
                               % (os.path.abspath(a.model), os.path.abspath(a.norm), a.out)))
    banner.append("// Model meta: %s" % meta)
    banner.append("//             seed=%s arch=%s" % (seed, blob.get("arch")))
    banner.append("//")
    banner.append("// Convention (mirrors src/alpaka/NeuralNetwork.h): weights are stored TRANSPOSED,")
    banner.append("// wgt[in][out], so the inference inner loop is output[o] += input[i] * wgt[i][o].")
    banner.append("//")
    banner.append("// Per-input preprocessing, applied in this order (bakes in the norm json's")
    banner.append('// "conditioning" spec):')
    banner.append("//   1. if (kLog10p1[i]) x = log10(1 + x)")
    banner.append("//   2. x = min(max(x, kClipLo[i]), kClipHi[i])   (+-1e30 = unclipped)")
    banner.append("//   3. x = (x - kFeatMean[i]) / kFeatStd[i]")
    banner.append("//")
    banner.append("// Input feature order (the LEADING %d slots of the PixelAttach.h kAttachFeat layout;" % n_in)
    banner.append("// AttachInference.cc feeds f[0..kInput-1], so this list must be a PREFIX of")
    banner.append("// PixelAttach.cc kAttachFeatNames):")
    for i, n in enumerate(names):
        banner.append("//  [%2d] %s" % (i, n))

    G = "RecoTracker_LSTCore_src_alpaka_AttachNetworkWeights_h"
    body = """{banner}
#ifndef {G}
#define {G}

#include <alpaka/alpaka.hpp>

#include "FWCore/Utilities/interface/HostDeviceConstant.h"

namespace ALPAKA_ACCELERATOR_NAMESPACE::lst::dnn::attachmlp {{

  constexpr int kInput = {n_in};
  constexpr int kHidden = {n_hid};

  HOST_DEVICE_CONSTANT float kFeatMean[kInput] = {kFeatMean};

  HOST_DEVICE_CONSTANT float kFeatStd[kInput] = {kFeatStd};

  HOST_DEVICE_CONSTANT float kClipLo[kInput] = {kClipLo};

  HOST_DEVICE_CONSTANT float kClipHi[kInput] = {kClipHi};

  HOST_DEVICE_CONSTANT bool kLog10p1[kInput] = {{{kLog10p1}}};

  HOST_DEVICE_CONSTANT float wgt_l1[kInput][kHidden] = {wgt_l1};

  HOST_DEVICE_CONSTANT float bias_l1[kHidden] = {bias_l1};

  HOST_DEVICE_CONSTANT float wgt_l2[kHidden][kHidden] = {wgt_l2};

  HOST_DEVICE_CONSTANT float bias_l2[kHidden] = {bias_l2};

  HOST_DEVICE_CONSTANT float wgt_out[kHidden] = {wgt_out};

  constexpr float bias_out = {bias_out};

}}  // namespace ALPAKA_ACCELERATOR_NAMESPACE::lst::dnn::attachmlp

#endif
""".format(banner="\n".join(banner), G=G, n_in=n_in, n_hid=n_hid,
           kFeatMean=arr1(mean), kFeatStd=arr1(std), kClipLo=arr1(clip_lo), kClipHi=arr1(clip_hi),
           kLog10p1=", ".join("true" if v else "false" for v in log10p1),
           wgt_l1=arr2(w1.T), bias_l1=arr1(b1), wgt_l2=arr2(w2.T), bias_l2=arr1(b2),
           wgt_out=arr1(wo[0]), bias_out=f32(bo[0]))

    if a.verify:
        ref = open(a.verify).read()
        if ref == body:
            print("PORT VERIFIED: byte-identical to %s" % a.verify)
        else:
            rl, bl = ref.splitlines(), body.splitlines()
            print("VERIFY FAILED: %d vs %d lines" % (len(rl), len(bl)))
            for i in range(min(len(rl), len(bl))):
                if rl[i] != bl[i]:
                    print("first diff at line %d:\n  ref: %r\n  new: %r" % (i + 1, rl[i], bl[i]))
                    break
            raise SystemExit(2)
    open(a.out, "w").write(body)
    print("wrote %s: kInput=%d kHidden=%d" % (a.out, n_in, n_hid))


if __name__ == "__main__":
    main()
